/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.banking;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashu
 */
public class AddMoneyDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddMoneyDialog
     */
    public AddMoneyDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void addMoney(int accountId, double amount, String description) {
        String updateBalanceSQL = "UPDATE Accounts SET balance = balance + ? WHERE account_id = ?";
        String insertTransactionSQL = "INSERT INTO Transactions (account_id, transaction_type, amount, balance_after_sender, description) " +
                                      "VALUES (?, 'deposit', ?, ?, ?)";

        try (Connection connection = MySQLConnection.getConnection();
             PreparedStatement updateBalanceStmt = connection.prepareStatement(updateBalanceSQL);
             PreparedStatement insertTransactionStmt = connection.prepareStatement(insertTransactionSQL)) {

            // Start transaction
            connection.setAutoCommit(false);

            // Update account balance
            updateBalanceStmt.setDouble(1, amount);
            updateBalanceStmt.setInt(2, accountId);
            int rowsUpdated = updateBalanceStmt.executeUpdate();

            if (rowsUpdated == 0) {
                connection.rollback();
                JOptionPane.showMessageDialog(null, "Account not found. Transaction failed.");
            }

            // Retrieve new balance
            double newBalance = getAccountBalance(connection, accountId);

            // Insert transaction record
            insertTransactionStmt.setInt(1, accountId);
            insertTransactionStmt.setDouble(2, amount);
            insertTransactionStmt.setDouble(3, newBalance);
            insertTransactionStmt.setString(4, description);
            insertTransactionStmt.executeUpdate();

            // Commit transaction
            connection.commit();
            JOptionPane.showMessageDialog(null, "Money added successfully. New Balance: " + newBalance);
            addAmount.setText("");
            descriptionAddMoney.setText("");
        } catch (SQLException e) {
            try {
                Connection connection = MySQLConnection.getConnection();
                connection.rollback();
            } catch (SQLException rollbackEx) {
                rollbackEx.printStackTrace();
            }
            e.printStackTrace();
            addAmount.setText("");
            descriptionAddMoney.setText("");
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        } finally {
            try {
                Connection connection = MySQLConnection.getConnection();
                connection.setAutoCommit(true);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    private double getAccountBalance(Connection connection, int accountId) throws SQLException {
        String query = "SELECT balance FROM Accounts WHERE account_id = ?";
        try (PreparedStatement stmt = connection.prepareStatement(query)) {
            stmt.setInt(1, accountId);
            var resultSet = stmt.executeQuery();
            if (resultSet.next()) {
                return resultSet.getDouble("balance");
            } else {
                throw new SQLException("Account not found");
            }
        }
    }

    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addAmount = new javax.swing.JTextField();
        addAmountButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        descriptionAddMoney = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add money");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 210, 204));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Add Money");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel5.setText("Enter Description :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, 25));

        addAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAmountActionPerformed(evt);
            }
        });
        jPanel2.add(addAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 110, 25));

        addAmountButton.setBackground(new java.awt.Color(255, 210, 204));
        addAmountButton.setText("Add");
        addAmountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAmountButtonActionPerformed(evt);
            }
        });
        jPanel2.add(addAmountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_rupee_20px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, 20));

        jLabel6.setText("Enter Amount :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, 25));
        jPanel2.add(descriptionAddMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 110, 25));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 220));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addAmountActionPerformed

    private void addAmountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAmountButtonActionPerformed
        double newMoney = Double.parseDouble(addAmount.getText());
        String description = descriptionAddMoney.getText();
        
        addMoney(LoginSignup.currentAccountId,newMoney,description);
    }//GEN-LAST:event_addAmountButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addAmount;
    private javax.swing.JButton addAmountButton;
    private javax.swing.JTextField descriptionAddMoney;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
