/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.banking;

/**
 *
 * @author Ashu
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        initialization();
    }
    
    /*I have used the tabbed pane with the absolute layout for better smooth switching from one window to another inside a single frame only*/
    
    //For setting the front homepage of the application that which tabbed pane should be opened at the time of starting the application
    private void initialization(){
        content.setSelectedIndex(0);
        login.setSelectedIndex(0);
        register.setSelectedIndex(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jDialog1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        content = new javax.swing.JTabbedPane();
        loginSignup = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        login = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lemail1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        register = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        rname = new javax.swing.JTextField();
        rname1 = new javax.swing.JTextField();
        rname2 = new javax.swing.JTextField();
        rname3 = new javax.swing.JTextField();
        rname4 = new javax.swing.JTextField();
        rname5 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rname6 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        rname7 = new javax.swing.JTextField();
        rname8 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        rname9 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        welcome = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logOut = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        welcomeName = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        welcomeName1 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Online Banking System");
        setLocationByPlatform(true);
        setName("Home"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Eras Demi ITC", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 25));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Online Banking System");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 560, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 80));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginSignup.setBackground(new java.awt.Color(51, 0, 25));
        loginSignup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(800, 475));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Eras Demi ITC", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 25));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("LOGIN YOUR ACCOUNT");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 40));

        jLabel26.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 0, 25));
        jLabel26.setText("USERNAME :");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 110, 30));

        jLabel27.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 0, 25));
        jLabel27.setText("PASSWORD :");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 110, 30));
        jPanel6.add(lemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 210, 30));

        jButton2.setBackground(new java.awt.Color(51, 0, 25));
        jButton2.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 204, 204));
        jButton2.setText("SIGNIN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 120, 40));

        jPasswordField1.setText("jPasswordField1");
        jPanel6.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 210, 30));

        login.addTab("tab1", jPanel6);

        jPanel7.setBackground(new java.awt.Color(64, 224, 208));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(105, 105, 105));
        jLabel20.setFont(new java.awt.Font("Eras Demi ITC", 0, 30)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 0, 25));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("ALREADY AN");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 400, 40));

        jLabel5.setBackground(new java.awt.Color(105, 105, 105));
        jLabel5.setFont(new java.awt.Font("Eras Demi ITC", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 25));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ACCOUNT?");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 400, 40));

        jLabel18.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 0, 25));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("CLICK ON THE SIGNIN BUTTON");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 400, 20));

        jLabel19.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 0, 25));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("TO LOGIN YOUR ACCOUNT");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 400, 20));

        jButton4.setBackground(new java.awt.Color(51, 0, 25));
        jButton4.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 204, 204));
        jButton4.setText("SIGNIN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 120, 40));

        login.addTab("tab2", jPanel7);

        jPanel5.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 400, 440));

        jPanel8.setBackground(new java.awt.Color(255, 204, 204));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Eras Demi ITC", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 25));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("REGISTER YOUR ACCOUNT");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, 30));

        jLabel12.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 25));
        jLabel12.setText("FULL NAME :");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 130, 30));

        jLabel9.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 25));
        jLabel9.setText("DOB :");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 130, 30));

        jLabel13.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 25));
        jLabel13.setText("GENDER :");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 130, 30));

        jLabel14.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 25));
        jLabel14.setText("FATHER'S NAME:");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 130, 30));

        jLabel16.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 25));
        jLabel16.setText("MOTHER'S NAME:");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 30));

        jLabel17.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 0, 25));
        jLabel17.setText("COUNTRY:");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 130, 30));

        rname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rnameActionPerformed(evt);
            }
        });
        jPanel8.add(rname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 200, 30));

        rname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rname1ActionPerformed(evt);
            }
        });
        jPanel8.add(rname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 200, 30));

        rname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rname2ActionPerformed(evt);
            }
        });
        jPanel8.add(rname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 200, 30));

        rname3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rname3ActionPerformed(evt);
            }
        });
        jPanel8.add(rname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 200, 30));

        rname4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rname4ActionPerformed(evt);
            }
        });
        jPanel8.add(rname4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 200, 30));

        rname5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rname5ActionPerformed(evt);
            }
        });
        jPanel8.add(rname5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 200, 30));

        jButton5.setBackground(new java.awt.Color(51, 0, 25));
        jButton5.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 204, 204));
        jButton5.setText("NEXT >>");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 120, 40));

        register.addTab("tab1", jPanel8);

        jPanel9.setBackground(new java.awt.Color(64, 224, 208));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(105, 105, 105));
        jLabel3.setFont(new java.awt.Font("Eras Demi ITC", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 25));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NEW HERE?");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 400, 40));

        jLabel6.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 25));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SIGNUP AND ENJOY GREAT");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 400, 20));

        jLabel4.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 25));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(" BANKING FACILITIES");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 400, 20));

        jButton3.setBackground(new java.awt.Color(51, 0, 25));
        jButton3.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 204, 204));
        jButton3.setText("SIGNUP");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 120, 40));

        register.addTab("tab2", jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 204, 204));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Eras Demi ITC", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 25));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("REGISTER YOUR ACCOUNT");
        jPanel10.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, 30));

        jLabel15.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 0, 25));
        jLabel15.setText("AADHAR NO:");
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 130, 30));

        rname6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rname6ActionPerformed(evt);
            }
        });
        jPanel10.add(rname6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 200, 30));

        jLabel21.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 0, 25));
        jLabel21.setText("MOBILE NO:");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 130, 30));

        rname7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rname7ActionPerformed(evt);
            }
        });
        jPanel10.add(rname7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 200, 30));

        rname8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rname8ActionPerformed(evt);
            }
        });
        jPanel10.add(rname8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 200, 30));

        jLabel22.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 0, 25));
        jLabel22.setText("EMAIL:");
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 130, 30));

        jLabel23.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 0, 25));
        jLabel23.setText("USERNAME:");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 130, 30));

        rname9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rname9ActionPerformed(evt);
            }
        });
        jPanel10.add(rname9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 200, 30));

        jLabel24.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 0, 25));
        jLabel24.setText("PIN:");
        jPanel10.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 30));

        jLabel25.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 0, 25));
        jLabel25.setText("CONFIRM PIN:");
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 130, 30));

        jButton6.setBackground(new java.awt.Color(51, 0, 25));
        jButton6.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 204, 204));
        jButton6.setText("SUBMIT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 120, 40));

        jPasswordField2.setText("jPasswordField2");
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPanel10.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 200, 30));

        jPasswordField3.setText("jPasswordField2");
        jPasswordField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField3ActionPerformed(evt);
            }
        });
        jPanel10.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 200, 30));

        register.addTab("tab3", jPanel10);

        jPanel5.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, -40, 400, 440));

        loginSignup.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 800, 400));

        content.addTab("Home", loginSignup);

        welcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(64, 224, 208));

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 25));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/banking/images/Home.png"))); // NOI18N
        jLabel1.setText(" Home");
        jLabel1.setPreferredSize(new java.awt.Dimension(169, 40));

        jLabel28.setFont(new java.awt.Font("Eras Demi ITC", 1, 20)); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/banking/images/Money Bag Rupee.png"))); // NOI18N
        jLabel28.setText(" Account");
        jLabel28.setPreferredSize(new java.awt.Dimension(169, 40));

        jLabel29.setFont(new java.awt.Font("Eras Demi ITC", 1, 20)); // NOI18N
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/banking/images/Initiate Money Transfer.png"))); // NOI18N
        jLabel29.setText(" Transfer");
        jLabel29.setPreferredSize(new java.awt.Dimension(169, 40));

        jLabel2.setFont(new java.awt.Font("Eras Demi ITC", 1, 20)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/banking/images/Payment History.png"))); // NOI18N
        jLabel2.setText(" Transactions");
        jLabel2.setPreferredSize(new java.awt.Dimension(169, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
        );

        welcome.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 85, 190, 440));

        jPanel2.setBackground(new java.awt.Color(51, 0, 25));

        logOut.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        logOut.setForeground(new java.awt.Color(255, 255, 255));
        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/banking/images/Logout.png"))); // NOI18N
        logOut.setText("LogOut");

        date.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("Your account balance is ");

        welcomeName.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        welcomeName.setForeground(new java.awt.Color(255, 255, 255));
        welcomeName.setText("Hi, Ashwani");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(719, 719, 719)
                .addComponent(logOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(logOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(welcomeName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        welcome.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 1000, 80));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane2.addTab("tab2", jPanel13);

        jPanel12.setBackground(new java.awt.Color(255, 204, 204));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(51, 0, 25));
        jPanel14.setFont(new java.awt.Font("Eras Demi ITC", 0, 20)); // NOI18N

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/banking/images/icons8_100%_100px.png"))); // NOI18N

        jLabel31.setFont(new java.awt.Font("Eras Demi ITC", 1, 15)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("PAY");

        jLabel32.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("A/C NUMBER **** 1568");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                .addGap(104, 104, 104))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addGap(167, 167, 167))
        );

        jLabel31.getAccessibleContext().setAccessibleParent(jLabel30);

        jPanel12.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 310, 360));

        jPanel15.setBackground(new java.awt.Color(51, 0, 25));

        welcomeName1.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        welcomeName1.setForeground(new java.awt.Color(255, 255, 255));
        welcomeName1.setText("Last Transactions");

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("See more...");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(welcomeName1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addGap(152, 152, 152))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(welcomeName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(133, 133, 133)
                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jPanel12.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 340, 200));

        jTabbedPane2.addTab("tab1", jPanel12);

        jPanel11.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 810, 480));

        welcome.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 85, 810, 440));

        content.addTab("Welcome", welcome);

        jPanel4.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1000, 560));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        login.setSelectedIndex(0);
        register.setSelectedIndex(1);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        login.setSelectedIndex(1);
        register.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void rnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rnameActionPerformed

    private void rname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rname1ActionPerformed

    private void rname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rname2ActionPerformed

    private void rname3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rname3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rname3ActionPerformed

    private void rname4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rname4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rname4ActionPerformed

    private void rname5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rname5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rname5ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        login.setSelectedIndex(1);
        register.setSelectedIndex(2);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void rname6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rname6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rname6ActionPerformed

    private void rname7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rname7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rname7ActionPerformed

    private void rname8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rname8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rname8ActionPerformed

    private void rname9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rname9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rname9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jPasswordField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField3ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane content;
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField lemail1;
    private javax.swing.JLabel logOut;
    private javax.swing.JTabbedPane login;
    private javax.swing.JPanel loginSignup;
    private javax.swing.JTabbedPane register;
    private javax.swing.JTextField rname;
    private javax.swing.JTextField rname1;
    private javax.swing.JTextField rname2;
    private javax.swing.JTextField rname3;
    private javax.swing.JTextField rname4;
    private javax.swing.JTextField rname5;
    private javax.swing.JTextField rname6;
    private javax.swing.JTextField rname7;
    private javax.swing.JTextField rname8;
    private javax.swing.JTextField rname9;
    private javax.swing.JPanel welcome;
    private javax.swing.JLabel welcomeName;
    private javax.swing.JLabel welcomeName1;
    // End of variables declaration//GEN-END:variables
}
